In [2]:
import numpy as np
import scipy.stats as st
import sklearn.linear_model as lm
import matplotlib.pyplot as plt
%matplotlib inline
import cv2

In [ ]:
def f(x):
    return np.exp(3 * x)

In [ ]:
x_tr = np.linspace(0., 2, 200)
y_tr = f(x_tr)

In [ ]:
x = np.array([0, .1, .2, .5, .8, .9, 1])
y = f(x) + 2 * np.random.randn(len(x))

In [ ]:
fig, ax = plt.subplots(1, 1, figsize=(6, 3))
ax.plot(x_tr, y_tr, '--k')
ax.plot(x, y, 'ok', ms=10)
ax.set_xlim(0, 1.5)
ax.set_ylim(-10, 80)
ax.set_title('Generative model')

In [11]:
#fichier="C:/Users/sophieGi/Documents/Binder/a.jpg"
#fichier= r"sdata/ArchivesData/VISIA/EXPORT/2019/Soft C Acne-OR242/Validation d'efficacité/19-02-04A Etude Porphyrines-UV/7-Front View-UV-NF 001.jpg"

fichier = r"\\sdata\ArchivesData\VISIA\EXPORT\2019\Soft C Acne-OR242\Validation d'efficacité\19-02-04A Etude Porphyrines-UV\7-Front View-UV-NF 001.jpg".decode('utf-8').encode('cp1252')

#print(fichier)

In [12]:
img = cv2.imread(fichier)
print(img)

[[[ 3  6  4]
  [ 2  5  3]
  [ 2  5  3]
  ..., 
  [ 4  4  4]
  [ 4  4  4]
  [ 4  4  4]]

 [[ 2  5  3]
  [ 2  5  3]
  [ 2  5  3]
  ..., 
  [ 4  4  4]
  [ 4  4  4]
  [ 4  4  4]]

 [[ 2  5  3]
  [ 2  5  3]
  [ 2  5  3]
  ..., 
  [ 4  4  4]
  [ 4  4  4]
  [ 3  3  3]]

 ..., 
 [[24 12  8]
  [24 12  8]
  [24 12  8]
  ..., 
  [27  8  5]
  [27  8  5]
  [27  8  5]]

 [[24 12  8]
  [24 12  8]
  [24 12  8]
  ..., 
  [27  8  5]
  [27  8  5]
  [26  7  4]]

 [[23 11  7]
  [23 11  7]
  [23 11  7]
  ..., 
  [27  8  5]
  [27  8  5]
  [26  7  4]]]


In [ ]:
cv2.imshow('image',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
fig, ax = plt.subplots()
im = ax.imshow(img)
plt.show()